env: none
server:
  port: 8756

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: springboot
    password: SpringBoot@123
    url: jdbc:mysql://192.168.8.116/selldb?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 192.168.8.116
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  profiles:
    active: prod

logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml